name: Run Lighthouse

on:
  push:
    branches:
      - main  # Możesz zmienić na inny branch, na przykład 'develop'
  pull_request:
    branches:
      - main  # W zależności od potrzeby, również pull requesty

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Wybierz wersję Node.js

      - name: Install dependencies
        run: npm install

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: lighthouse http://localhost:3000 --output html --output-path ./lighthouse-report.html

      - name: Upload Lighthouse Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html
